### ISSUE TITLE
The conditional check '(item.content in aemLoad.content)' failed

### ISSUE THREAD

**Issue by dzmitry-rudnouski** [lean-delivery/ansible-role-aem-node#17]
##### SUMMARY
Error at first run only, second run is ok.

fatal: [ubuntu@xx.xx.xx.xx]: FAILED! => {"msg": "The conditional check '(item.content in aemLoad.content)' failed. The error was: error while evaluating conditional ((item.content in aemLoad.content)): Unable to look up a name or access an attribute in template string ({% if (item.content in aemLoad.content) %} True {% else %} False {% endif %}).\nMake sure your variable name does not contain invalid characters like '-': argument of type 'AnsibleUndefined' is not iterable"}

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
ansible 2.8.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
```

##### OS / ENVIRONMENT
Ubuntu 18.04

##### STEPS TO REPRODUCE
Run playbook

```yaml
---
- hosts: localhost
  gather_facts: False
  vars:
    repo_url: "{{ lookup('env','repo_url') | default('https://github.com/lean-delivery/ansible-modules-aem.git', true)}}"
    modules_path: "{{ lookup('env','ansible_modules_path') | default('~/.ansible/plugins/modules', true)}}"
    modules_version: "{{ lookup('env','ansible_modules_version') | default('develop', true)}}"
  tasks:
    - name: Make sure that modules directory is exists
      file:
        path: "{{ modules_path }}"
        state: directory
        mode: 0755
    - name: Install Ansible AEM Modules
      git:
        repo: "{{ repo_url }}"
        dest: "{{ modules_path }}/ansible-modules-aem"
        version: "{{ modules_version }}"
        force: yes 

- name: java_install
  hosts: all
  roles:
    - role: lean_delivery.java
      transport: repositories
      java_major_version: 8

- name: publisher_install
  hosts: aem_publishers
  roles:
    - role: ../ansible-role-aem-node
      replication_enabled: true
      aem_instance_type: publish
      download_transport: s3
      transport_s3_bucket: mybucket
      aem_transport_s3_path: '/static/aem/{{ aem_version }}/aem.jar'
      license_transport_s3_path: '/static/aem/licenses/{{ aem_version }}/license.properties'
      aem_groups:
       -
        id: 'test_group'
        name: 'Test'
        description: 'All test users'
        permissions:
          - 'path:/,read:true'
          - 'path:/etc/packages,read:true,modify:true,create:true,delete:false,replicate:true'
        root_groups:
          - 'everyone'
      aem_users:
       -
        category: 'test'
        id: 'test_user'
        first_name: 'Test'
        second_name: 'User'
        password: 'Test_user_password1'
        group: 'test_group'


- name: author_install
  hosts: aem_authors

  roles:
    - role: ../ansible-role-aem-node
      replication_enabled: true
      aem_instance_type: author
      download_transport: s3
      transport_s3_bucket: mybucket
      aem_transport_s3_path: '/static/aem/{{ aem_version }}/aem.jar'
      license_transport_s3_path: '/static/aem/licenses/{{ aem_version }}/license.properties'
      publishers: "{{ groups['aem_publishers'] }}"
      aem_groups:
       -
        id: 'test_group'
        name: 'Test'
        description: 'All test users'
        permissions:
          - 'path:/,read:true'
          - 'path:/etc/packages,read:true,modify:true,create:true,delete:false,replicate:true'
        root_groups:
          - 'everyone'
      aem_users:
       -
        category: 'test'
        id: 'test_user'
        first_name: 'Test'
        second_name: 'User'
        password: 'Test_user_password1'
        group: 'test_group'
```
