### ISSUE TITLE
Failed with non-default port

### ISSUE THREAD

**Issue by dzmitry-rudnouski** [lean-delivery/ansible-role-aem-node#19]
##### SUMMARY
Failed with non-default port

`
TASK [../ansible-role-aem-node : add a new Test group] **********************************************************************************************************************************************
fatal: [ubuntu@3.248.207.190]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 3.248.207.190 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/usr/lib/python3/dist-packages/urllib3/connection.py\", line 141, in _new_conn\r\n    (self.host, self.port), self.timeout, **extra_kw)\r\n  File \"/usr/lib/python3/dist-packages/urllib3/util/connection.py\", line 83, in create_connection\r\n    raise err\r\n  File \"/usr/lib/python3/dist-packages/urllib3/util/connection.py\", line 73, in create_connection\r\n    sock.connect(sa)\r\nConnectionRefusedError: [Errno 111] Connection refused\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/usr/lib/python3/dist-packages/urllib3/connectionpool.py\", line 601, in urlopen\r\n    chunked=chunked)\r\n  File \"/usr/lib/python3/dist-packages/urllib3/connectionpool.py\", line 357, in _make_request\r\n    conn.request(method, url, **httplib_request_kw)\r\n  File \"/usr/lib/python3.6/http/client.py\", line 1254, in request\r\n    self._send_request(method, url, body, headers, encode_chunked)\r\n  File \"/usr/lib/python3.6/http/client.py\", line 1300, in _send_request\r\n    self.endheaders(body, encode_chunked=encode_chunked)\r\n  File \"/usr/lib/python3.6/http/client.py\", line 1249, in endheaders\r\n    self._send_output(message_body, encode_chunked=encode_chunked)\r\n  File \"/usr/lib/python3.6/http/client.py\", line 1036, in _send_output\r\n    self.send(msg)\r\n  File \"/usr/lib/python3.6/http/client.py\", line 974, in send\r\n    self.connect()\r\n  File \"/usr/lib/python3/dist-packages/urllib3/connection.py\", line 166, in connect\r\n    conn = self._new_conn()\r\n  File \"/usr/lib/python3/dist-packages/urllib3/connection.py\", line 150, in _new_conn\r\n    self, \"Failed to establish a new connection: %s\" % e)\r\nurllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fa27dd99748>: Failed to establish a new connection: [Errno 111] Connection refused\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/usr/lib/python3/dist-packages/requests/adapters.py\", line 440, in send\r\n    timeout=timeout\r\n  File \"/usr/lib/python3/dist-packages/urllib3/connectionpool.py\", line 639, in urlopen\r\n    _stacktrace=sys.exc_info()[2])\r\n  File \"/usr/lib/python3/dist-packages/urllib3/util/retry.py\", line 398, in increment\r\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\r\nurllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4502): Max retries exceeded with url: /bin/querybuilder.json?path=/home/groups&1_property=rep:authorizableId&1_property.value=test_group&p.limit=-1&p.hits=full (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa27dd99748>: Failed to establish a new connection: [Errno 111] Connection refused',))\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1576503478.4485545-170197019787983/AnsiballZ_aem_group.py\", line 114, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1576503478.4485545-170197019787983/AnsiballZ_aem_group.py\", line 106, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1576503478.4485545-170197019787983/AnsiballZ_aem_group.py\", line 49, in invoke_module\r\n    imp.load_module('__main__', mod, module, MOD_DESC)\r\n  File \"/usr/lib/python3.6/imp.py\", line 235, in load_module\r\n    return load_source(name, filename, file)\r\n  File \"/usr/lib/python3.6/imp.py\", line 170, in load_source\r\n    module = _exec(spec, sys.modules[name])\r\n  File \"<frozen importlib._bootstrap>\", line 618, in _exec\r\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\r\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\r\n  File \"/tmp/ansible_aem_group_payload_b47w7gri/__main__.py\", line 357, in <module>\r\n  File \"/tmp/ansible_aem_group_payload_b47w7gri/__main__.py\", line 340, in main\r\n  File \"/tmp/ansible_aem_group_payload_b47w7gri/__main__.py\", line 130, in __init__\r\n  File \"/tmp/ansible_aem_group_payload_b47w7gri/__main__.py\", line 140, in get_group_info\r\n  File \"/usr/lib/python3/dist-packages/requests/api.py\", line 72, in get\r\n    return request('get', url, params=params, **kwargs)\r\n  File \"/usr/lib/python3/dist-packages/requests/api.py\", line 58, in request\r\n    return session.request(method=method, url=url, **kwargs)\r\n  File \"/usr/lib/python3/dist-packages/requests/sessions.py\", line 520, in request\r\n    resp = self.send(prep, **send_kwargs)\r\n  File \"/usr/lib/python3/dist-packages/requests/sessions.py\", line 630, in send\r\n    r = adapter.send(request, **kwargs)\r\n  File \"/usr/lib/python3/dist-packages/requests/adapters.py\", line 508, in send\r\n    raise ConnectionError(e, request=request)\r\nrequests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=4502): Max retries exceeded with url: /bin/querybuilder.json?path=/home/groups&1_property=rep:authorizableId&1_property.value=test_group&p.limit=-1&p.hits=full (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa27dd99748>: Failed to establish a new connection: [Errno 111] Connection refused',))\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
`

##### ISSUE TYPE
 - Bug Report

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  gather_facts: False
  vars:
    repo_url: "{{ lookup('env','repo_url') | default('https://github.com/lean-delivery/ansible-modules-aem.git', true)}}"
    modules_path: "{{ lookup('env','ansible_modules_path') | default('~/.ansible/plugins/modules', true)}}"
    modules_version: "{{ lookup('env','ansible_modules_version') | default('develop', true)}}"
  tasks:
    - name: Make sure that modules directory is exists
      file:
        path: "{{ modules_path }}"
        state: directory
        mode: 0755
    - name: Install Ansible AEM Modules
      git:
        repo: "{{ repo_url }}"
        dest: "{{ modules_path }}/ansible-modules-aem"
        version: "{{ modules_version }}"
        force: yes 

- name: java_install
  hosts: all
  roles:
    - role: lean_delivery.java
      transport: repositories
      java_major_version: 8

- name: publisher_install
  hosts: aem_publishers
  roles:
    - role: ../ansible-role-aem-node
      replication_enabled: true
      aem_instance_type: publish
      aem_instance_port: 4503
      aem_custom_modes: nosamplecontent
      download_transport: s3
      transport_s3_bucket: mybucket
      aem_transport_s3_path: '/static/aem/{{ aem_version }}/aem.jar'
      license_transport_s3_path: '/static/aem/licenses/{{ aem_version }}/license.properties'
      aem_groups:
       -
        id: 'test_group'
        name: 'Test'
        description: 'All test users'
        permissions:
          - 'path:/,read:true'
          - 'path:/etc/packages,read:true,modify:true,create:true,delete:false,replicate:true'
        root_groups:
          - 'everyone'
      aem_users:
       -
        category: 'test'
        id: 'test_user'
        first_name: 'Test'
        second_name: 'User'
        password: 'Test_user_password1'
        group: 'test_group'
```
